#Test v1.0
#Fri Apr 24 08:46:46 GMT-03:00 2026
app.name=PropertiesApi
database.url=jdbc\:postgresql\://localhost\:5432/test
signin=Authenticated successfully
signup=Registered successfully
version=2.0
